###

GET http://localhost:3001/post

###

GET http://localhost:3001/post/123456

###

POST http://localhost:3001/post
Content-Type: application/json

{
    "message": "this is a new message",
    "sender": "Otyr"
}