###

GET http://localhost:3001/post

###

GET http://localhost:3001/post/post?sender=Otyr

###

GET http://localhost:3001/post/6761ced3e67abb29629a6608

###

POST http://localhost:3001/post
Content-Type: application/json

{
    "message": "this is a new message",
    "sender": "Otyr"
}