###

GET http://localhost:3001/post

###

GET http://localhost:3001/post?sender=Otyr

###

GET http://localhost:3001/post/67653ac115ecd6c261b46cab

###

POST http://localhost:3001/post
Content-Type: application/json

{
    "message": "this is a new message",
    "sender": "Otyr"
}